// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzp2n7Wi7KHVYXCTj1wpUYinvuz4iRdY4',
    appId: '1:162337146243:web:711fe9dbc4e797d25b22b6',
    messagingSenderId: '162337146243',
    projectId: 'cloudfirebase-1f8fa',
    authDomain: 'cloudfirebase-1f8fa.firebaseapp.com',
    storageBucket: 'cloudfirebase-1f8fa.appspot.com',
    measurementId: 'G-8216XF67F8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm_U4MogrRt-TGsvLG0w6PIY7pisQFn4U',
    appId: '1:162337146243:android:1c6cd9a3a35883525b22b6',
    messagingSenderId: '162337146243',
    projectId: 'cloudfirebase-1f8fa',
    storageBucket: 'cloudfirebase-1f8fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPsdC9r7j2PahDPBdow8ojwqbN4XF9Kso',
    appId: '1:162337146243:ios:b593dba5b000eecd5b22b6',
    messagingSenderId: '162337146243',
    projectId: 'cloudfirebase-1f8fa',
    storageBucket: 'cloudfirebase-1f8fa.appspot.com',
    iosBundleId: 'com.flutive.cloudFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPsdC9r7j2PahDPBdow8ojwqbN4XF9Kso',
    appId: '1:162337146243:ios:b593dba5b000eecd5b22b6',
    messagingSenderId: '162337146243',
    projectId: 'cloudfirebase-1f8fa',
    storageBucket: 'cloudfirebase-1f8fa.appspot.com',
    iosBundleId: 'com.flutive.cloudFirebaseApp',
  );
}
